# Generated by Django 5.2 on 2025-05-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('loan', 'Loan'), ('debt', 'Debt'), ('savings', 'Savings'), ('other', 'Other')], max_length=20),
        ),
    ]
