services:
  - type: web
    name: finance-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        value: your-secret-key
      - key: DB_NAME
        fromDatabase:
          name: finance_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: finance_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: finance_db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: finance_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: finance_db
          property: port

databases:
  - name: finance_db
    databaseName: api_transaction
    user: angeladmin
