services:
  - type: web
    name: finance-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: DB_NAME
        fromDatabase:
          name: simulator_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: simulator_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: simulator_db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: simulator_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: simulator_db
          property: port

databases:
  - name: simulator_db
    databaseName: simulator_ftte
    user: simulator_user
