# Generated by Django 5.2 on 2025-08-08 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='receipt', help_text='Nombre del ícono (lucide-react)', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Color hexadecimal para gráficos', max_length=7)),
                ('category_type', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso'), ('both', 'Ambos')], default='expense', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='transactions.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('investment', 'Investment'), ('loan', 'Loan'), ('debt', 'Debt'), ('savings', 'Savings'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Número de referencia/voucher', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Lugar de la transacción', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Etiquetas: ['comida', 'trabajo']")),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category')),
                ('from_account', models.ForeignKey(help_text='Cuenta de origen (obligatorio para gastos/transferencias)', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='accounts.account')),
                ('parent_transaction', models.ForeignKey(blank=True, help_text='Transacción padre si es recurrente', null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
                ('to_account', models.ForeignKey(blank=True, help_text='Cuenta destino (para ingresos/transferencias)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
