# Generated by Django 5.2 on 2025-08-08 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, help_text='Cuenta de origen (para gastos/transferencias)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='accounts.account'),
        ),
    ]
