# Generated by Django 5.2 on 2025-08-08 21:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Cuenta Corriente BCP', max_length=100)),
                ('bank_name', models.CharField(blank=True, help_text='Ej: BCP, BBVA, Interbank', max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Últimos 4 dígitos (opcional)', max_length=50)),
                ('account_type', models.CharField(choices=[('checking', 'Cuenta Corriente'), ('savings', 'Cuenta Ahorros'), ('investment', 'Cuenta Inversión'), ('credit', 'Tarjeta Crédito'), ('cash', 'Efectivo'), ('digital_wallet', 'Billetera Digital'), ('business', 'Cuenta Empresarial'), ('other', 'Otros')], default='checking', max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='PEN', help_text='PEN, USD, EUR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('include_in_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['bank_name', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
