# Generated by Django 5.2 on 2025-08-08 21:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('budget_exceeded', 'Presupuesto Excedido'), ('unusual_expense', 'Gasto Inusual'), ('income_drop', 'Caída de Ingresos'), ('account_low', 'Saldo Bajo'), ('category_spike', 'Pico en Categoría')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.account')),
                ('related_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='transactions.category')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Presupuesto',
                'verbose_name_plural': 'Alertas de Presupuesto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('average_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('previous_period_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('percentage_change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='transactions.category')),
                ('most_used_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_used_for_categories', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen de Categoría',
                'verbose_name_plural': 'Resúmenes de Categorías',
                'ordering': ['-total_amount'],
                'unique_together': {('user', 'category', 'period_start', 'period_end', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='FinancialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('checking_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('investment_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('top_expense_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('top_expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_expense_periods', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrica Financiera',
                'verbose_name_plural': 'Métricas Financieras',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period_type', 'period_start', 'period_end')},
            },
        ),
    ]
